name: Test Site
favicon: null
layout_spectrum: 0.79646
typography_spectrum: 0.73053
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f5f0'
    - '#afd8f4'
    - '#968a8e'
    - '#000000'
    - '#584733'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.25975291384384036
purpose: []
